import type {Metadata} from 'next';
import './globals.css';
import {AuthContext, useAuthSubscription} from '@/lib/auth';
import {AppSidebar} from '@/components/app-sidebar';

export const metadata: Metadata = {
  title: 'LaVicel Travel and Tours',
  description: 'Generated by Firebase Studio',
};

function AuthProvider({children}: {children: React.ReactNode}) {
  'use client';
  const authState = useAuthSubscription();
  return (
    <AuthContext.Provider value={authState}>{children}</AuthContext.Provider>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-body antialiased">
        <AuthProvider>
          <div className="flex">
            <AppSidebar />
            <main className="flex-1">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
